digitalocean/Kubernetes-Starter-Kit-Developers

5-setup-loki-stack/README.md
5-setup-loki-stack/res/manifests/loki-values.yaml
5-setup-loki-stack/res/manifests/loki_do_spaces_lifecycle.xml

* Explain the options available for storage retention based on either the `Table Manager` or `Compactor`
* Add `S3` storage retention policy options and example

Use either table manager or compactor retention options, added S3 storage policy example

---

5-setup-loki-stack/README.md
5-setup-loki-stack/res/manifests/loki-values.yaml
5-setup-loki-stack/res/manifests/loki_do_spaces_lifecycle.xml

* Explain why we choose to use `S3` compatible storage in general
* **Do not confuse the user** with `unnecessary` details about storage retention details like `Table Manager` and `Compactor`
* Give just a `simple` example on how to set retention for `DO Spaces`
* Grammar fixes and sentences simplification

Simplify Loki storage retention section

---

3-setup-ingress-ambassador/README.md
3-setup-ingress-ambassador/res/manifests/ambassador-values.yaml
3-setup-ingress-ambassador/res/manifests/echo_host.yaml
3-setup-ingress-ambassador/res/manifests/echo_mapping.yaml
3-setup-ingress-ambassador/res/manifests/quote_host.yaml
3-setup-ingress-ambassador/res/manifests/quote_mapping.yaml
4-setup-prometheus-stack/README.md

* Use a proper name for the domain and update all the references.
* AES performance analysis and considerations

AES performance analysis and considerations

---

5-setup-loki-stack/README.md
5-setup-loki-stack/res/manifests/loki-stack-values-v2.4.1.yaml

Pretty much as the title says, try to follow the `DO` best practices and `PDOC` guides:
- Use the procedural style as much as possible.
- Guide the user on each step, and explain the goals.
- Try to adhere to the `Voice` and `Tone` guides.
- Simplify the steps ,and try not to confuse the user with unnecessary details.

Refactor Loki tutorial according to DO style

---

3-setup-ingress-ambassador/README.md
4-setup-prometheus-stack/README.md

- In the AES installation area move the note.
- Minor change the LB introduction.
- Linked the yaml file in mapping AES Mappings for Hosts
- Added note for the delay in propagation
- Added note about the Grafana localhost and login credentials.

Updated README.md for Ingress-ambassador & Prometheus

---

1-setup-DOKS/README.md

Pretty much as the title says, try to follow the `DO` best practices and `PDOC` guides:
- Use the procedural style as much as possible.
- Guide the user on each step, and explain the goals.
- Try to adhere to the `Voice` and `Tone` guides.
- Added some missing details about the used commands along the tutorial.

[DOKS Setup] - Documentation refactoring, align to DO style

---

15-automate-with-terraform-flux/README.md
15-automate-with-terraform-flux/assets/terraform/main.tf

- Changed the location Step 1 [OPTIONAL] - Initialize the Terraform Backend
- Add note about exploring cluster option
- Corrected typo in Kubernetes-Starter-Kit-Developers/15-automate-with-terraform-flux/assets/terraform/main.tf

Minor changes in automation-flux-terraform

---

08-kubernetes-sealed-secrets/README.md

Fixes #64
- Explain to the user why we choose `Sealed Secrets` over existing solutions, like `Vault` for example (provided some of the missing features, as well).
- Added the `Security Best Practices` section, to explain some basic concepts that can be applied to create a more secure `Sealed Secrets` deployment.
- Tutorial layout small fixes.

08-kubernetes-sealed-secrets feedback

---

03-setup-ingress-controller/ambassador.md
03-setup-ingress-controller/assets/manifests/ambassador-values-v6.7.13.yaml
03-setup-ingress-controller/assets/manifests/nginx-values-v4.0.6.yaml
03-setup-ingress-controller/nginx.md

Fixes #91 
- Enables/Disable proxy protocol for Ingress Controller (Nginx or Ambassador) from

[Issue #91] Fix proxy protocol issue from the Ingress Controller

---

15-automate-with-terraform-flux/assets/terraform/backend.tf.sample
15-automate-with-terraform-flux/assets/terraform/main.tf.sample

This PR updates the `tf.sample` files by changing the DOKS version of Kubernetes to `1.21.5-do.0` and changing some of the prompts from questions to statements.

update tf.sample config files

---

03-setup-ingress-controller/assets/manifests/nginx-values-v4.0.6.yaml
04-setup-prometheus-stack/assets/manifests/prom-stack-values-v17.1.3.yaml

- Added monitoring metrics values for Nginx Ingress

Monitoring metrics values for Nginx Ingress Controller

---

README.md

Added badges with version for every helm chart used in the project in order to help the reader which version are used in the main branch

Added badges with version for every helm chart used in the project

---

README.md

* Fixed [MD045](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md045---images-should-have-alternate-text-alt-text) for badges
* Added a small note about tags and what we should use them

Added a note for tags

---

01-setup-DOKS/README.md

The DO K8s version used has been updated to the latest version

Updated DO K8s version from 1.21.3 to 1.21.5

---

06-setup-backup-restore/assets/manifests/velero-values-v2.27.3.yaml
06-setup-backup-restore/velero.md

Updated Velero from version 2.23.6 to 2.27.3

Updated Velero from version 2.23.6 to 2.27.3

---

README.md

Updated badges picture with the helm chart version tested

Updated badges from the README

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Created multiple issuet emplates in order to help the developer to raise correctly in case of a problem, or a feature is need it or a just a discussion

Added issue templates 

---

15-automate-with-terraform-flux/README.md
15-automate-with-terraform-flux/assets/manifests/fluxcd/helm/releases/ambassador-stack-v7.2.2.yaml
15-automate-with-terraform-flux/assets/manifests/fluxcd/helm/repositories/ambassador.yaml

* Updated Ambassador to version 7.2.2

Updated Ambassador in the automation chapter

---

04-setup-prometheus-stack/assets/manifests/prom-stack-values-v30.0.1.yaml
05-setup-loki-stack/README.md
05-setup-loki-stack/assets/manifests/loki-stack-values-v2.5.1.yaml
06-setup-backup-restore/assets/manifests/triliovault/starter-kit-cluster-backup-plan.yaml
06-setup-backup-restore/trilio.md
15-automate-with-terraform-flux/assets/manifests/fluxcd/helm/releases/loki-stack-v2.5.1.yaml
15-automate-with-terraform-flux/assets/manifests/fluxcd/helm/releases/prometheus-stack-v30.0.1.yaml

* Changed loki namespace to loki-stack from monitoring
* Added persistent storage using DO Volumes in the loki-stack value file

Changed loki namespace to loki-stack

---

08-kubernetes-sealed-secrets/README.md
15-automate-with-terraform-flux/README.md

Kubeseal CLI not able to export the Sealed Secrets controller public certificate

---

03-setup-ingress-controller/assets/manifests/nginx/echo_host.yaml
03-setup-ingress-controller/assets/manifests/nginx/quote_host.yaml
03-setup-ingress-controller/assets/manifests/nginx/wildcard-host.yaml

Fixed wrong service port number for ingress host rules

---

01-setup-DOKS/README.md
06-setup-backup-restore/trilio.md
07-alerting-and-notification/README.md

Fixing markdown violation MD031
Fixing the following markdwon violation: MD012 and MD041

Fixing markdown violation

---

03-setup-ingress-controller/assets/manifests/nginx/echo_host.yaml
03-setup-ingress-controller/assets/manifests/nginx/quote_host.yaml

Fixed static sub-domain TLS Certificates for Nginx

---

.github/workflows/markdown.yml
.github/workflows/test.yml

Removed development from environment this is not need it

Removed environment deployment

---

01-setup-DOKS/README.md
04-setup-prometheus-stack/README.md
04-setup-prometheus-stack/assets/manifests/prom-stack-values-v35.5.1.yaml

- updates chapter 1 with an optional step in relation to creating the new observability node
- adds labels to node to be used later with nodeAffinity
- adds nodeAffinity specs for observability chapter 4

Adding new optional node and configuration for observability

---

15-continuous-delivery-using-gitops/argocd.md

Argo version was set to old version in step 4 of the helm based installation section.

Corrects version in step 4 of helm installation

---

14-continuous-delivery-using-gitops/fluxcd.md

[Continuous Delivery using GitOps] Fixed FluxCD guide links due to main CD chapter folder refactoring
